# TODO:
# DONE: Double + Dueling + N step

description:  not finished yet
seed: 0

# 环境
env_name: LunarLander-v2
env_name: CartPole-v1
gamma: 0.99

# 模型
hidden_dim: 64
hidden_num: 2
activation_fn: relu

# 算法
no_double: True
no_dueling: True
n_step: 1
copy_interval: 500
epsilon_start: 1  # linear decay to 0
buffer_size: 10000

# 训练
max_step: 5_0000  # 训练次数
lr: 1.e-4
batch_size: 64

# 测试
test_interval: 1000
