description: 试试采样使用随机策略能不能收敛, 如果可以说明DQN不依赖于采样策略

# 环境
env_name: CartPole-v1
env_name: LunarLander-v2
gamma: 0.99

# 模型
hidden_dim: 32
hidden_num: 2
activation_fn: relu

# 算法
copy_interval: 1000
epsilon_start: 1  # linear decay to 0
buffer_size: 10000

# 训练
max_step: 5_0000  # 训练次数
lr: 1.e-4
batch_size: 128

# 测试
test_interval: 1000
